name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  provide_packages_json:
    runs-on: self-hosted
    # here, we save the result of this 1st phase to the "outputs"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
            
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
              
      - name: Run uipcli tests
        id: set-matrix
        env:
            CLIENT_ID: ${{ secrets.CLIENT_ID }}
            CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
            SCOPE: ${{ secrets.SCOPE }}
            OR_TENANT: ${{ vars.OR_TENANT }}
            ACCOUNTFORAPP: ${{ vars.ACCOUNTFORAPP }}
            
        run: echo "matrix=$(jq -c . (.\.github\workflows\test.ps1))" >> $GITHUB_OUTPUT
       
  run_tests:
    needs: provide_packages_json
    runs-on: self-hosted
    strategy:
      # ↓ the real magic happens here - create dynamic matrix from the json
      matrix:
        package: ${{ fromJson(needs.provide_packages_json.outputs.matrix) }}
    steps:
       - name: Run uipcli tests
         shell: pwsh
         run: echo ${{ matrix.name }}