name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
              
      - name: Run uipcli tests
        shell: pwsh
        env:
            CLIENT_ID: ${{ secrets.CLIENT_ID }}
            CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
            SCOPE: ${{ secrets.SCOPE }}
            OR_TENANT: ${{ vars.OR_TENANT }}
            ACCOUNTFORAPP: ${{ vars.ACCOUNTFORAPP }}
            
        run: pwsh -File "$Env:GITHUB_WORKSPACE\.github\workflows\test.ps1"
