name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out UiPath tests with GitHub Actions 🚀
on: [push]
jobs:
  provide_packages_json:
    runs-on: self-hosted
    # here, we save the result of this 1st phase to the "outputs"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
            
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
              
      - name: Run script to create test matrix
        id: set-matrix
        shell: pwsh
        env:
            CLIENT_ID: ${{ secrets.CLIENT_ID }}
            CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
            SCOPE: ${{ secrets.SCOPE }}
            OR_TENANT: ${{ vars.OR_TENANT }}
            ACCOUNTFORAPP: ${{ vars.ACCOUNTFORAPP }}
            
        run: |
          $cmdOutput = (.\getTestSets.ps1)
          echo "matrix=$cmdOutput"
          echo "::set-output name=matrix::$($cmdOutput)"
       
  run_tests:
    name: Run test set ${{ matrix.testsetname }} in folder ${{ matrix.orgunitname }}
    needs: provide_packages_json
    permissions: write-all
    runs-on: self-hosted
    strategy:
      # ↓ the real magic happens here - create dynamic matrix from the json
      matrix: ${{ fromJson(needs.provide_packages_json.outputs.matrix) }}
    steps:
       - name: Checkout repository
         uses: actions/checkout@v2

       - name: Setup UiPath CLI
         uses: Mikael-RnD/setup-uipath@v1.1.37
         
      
       - name: Run UiPath Test Set 
         shell: pwsh
         env:
            CLIENT_ID: ${{ secrets.CLIENT_ID }}
            CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
            SCOPE: ${{ secrets.SCOPE }}
            OR_TENANT: ${{ vars.OR_TENANT }}
            ACCOUNTFORAPP: ${{ vars.ACCOUNTFORAPP }}
            
         run: uipcli.exe test run "https://cloud.uipath.com/" ${{env.OR_TENANT}} --accountForApp ${{env.ACCOUNTFORAPP}} --applicationId ${{env.CLIENT_ID}} --applicationSecret "${{env.CLIENT_SECRET}}" --applicationScope "${{env.SCOPE}}" --testset ${{ matrix.testsetname }} --organizationUnit ${{ matrix.orgunitname }} --traceLevel 1 --attachRobotLogs --result_path ".\TestResults\TEST-${{ matrix.testsetname }}.xml"  --out junit  



       - name: Test Report
         uses: dorny/test-reporter@v1
         if: success() || failure()    # run this step even if previous step failed
         with:
           name: UiPath Tests            # Name of the check run which will be created
           path: TestResults/TEST-*.xml    # Path to test results
           reporter: java-junit        # Format of test results
           
